"""
Stage 6 — output.py

Produce the final artefacts from the validated selector list:
  1. A JSON configuration string (scraper_config.json content)
  2. A ready-to-run Python / BeautifulSoup snippet string
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from typing import List, Tuple


def build_output(
    validated_selectors: List[dict],
    source_url: str | None = None,
) -> Tuple[str, str]:
    """
    Build and return ``(config_json, snippet_py)`` as strings.

    Parameters
    ----------
    validated_selectors:
        Output of validator.validate() — each dict must have at minimum
        the keys produced by reasoner + validator stages.
    source_url:
        Original URL the HTML was fetched from, or None.

    Returns
    -------
    config_json : str
        Pretty-printed JSON configuration.
    snippet_py : str
        Working Python / BeautifulSoup scraper script.
    """
    config_json = _build_config_json(validated_selectors, source_url)
    snippet_py = _build_snippet(validated_selectors, source_url)
    return config_json, snippet_py


# ---------------------------------------------------------------------------
# Internal helpers
# ---------------------------------------------------------------------------

def _build_config_json(selectors: List[dict], source_url: str | None) -> str:
    """Serialise validated selectors to a JSON configuration string."""
    config = {
        "source_url": source_url or None,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "fields": selectors,
    }
    return json.dumps(config, indent=2, ensure_ascii=False)


def _build_snippet(selectors: List[dict], source_url: str | None) -> str:
    """Generate a working Python BeautifulSoup scraper script."""
    url_value = source_url if source_url else "YOUR_URL_HERE"

    # Only emit extraction lines for fields that actually matched
    valid_selectors = [s for s in selectors if s.get("valid", False)]

    lines: List[str] = [
        "import requests",
        "from bs4 import BeautifulSoup",
        "",
        f'url = "{url_value}"',
        'response = requests.get(url, headers={"User-Agent": "Mozilla/5.0"})',
        'soup = BeautifulSoup(response.text, "lxml")',
        "",
        "# Generated by Scout",
        "results = {}",
    ]

    for sel in valid_selectors:
        field_name: str = sel.get("field_name", "field")
        css_selector: str = sel.get("css_selector", "")
        match_count: int = sel.get("match_count", 1)

        # Sanitise field_name to be a valid Python identifier key (keep as string key)
        safe_name = field_name.replace('"', '\\"')
        safe_css = css_selector.replace('"', '\\"')

        warning = sel.get("warning")
        if warning:
            lines.append(f"# Warning: {warning}")

        if match_count == 1:
            # Single element — use select_one
            lines.append(
                f'results["{safe_name}"] = soup.select_one("{safe_css}").get_text(strip=True)'
            )
        else:
            # Multiple elements — use select and collect all texts
            lines.append(
                f'results["{safe_name}"] = '
                f'[el.get_text(strip=True) for el in soup.select("{safe_css}")]'
            )

    lines.append("")
    lines.append("print(results)")

    return "\n".join(lines)
