"""
Stage 5 — validator.py

Confirm that the CSS selectors generated by the reasoner actually match
elements in the original source HTML.
"""

from __future__ import annotations

import logging
from typing import List

from bs4 import BeautifulSoup

logger = logging.getLogger(__name__)

# Maximum characters from the first matched element to store as a sample
MATCH_SAMPLE_LENGTH = 100


def validate(selectors: List[dict], html: str) -> List[dict]:
    """
    For each selector in *selectors*, run `soup.select(css_selector)` against
    *html* and record:
        match_count  — number of elements matched
        match_sample — first MATCH_SAMPLE_LENGTH chars of first match text (or None)
        valid        — True if match_count >= 1

    If valid is False, append "⚠ No match found" to the warning field.

    Returns the same list with those fields added (operates on copies).
    """
    if not selectors:
        return []

    try:
        soup = BeautifulSoup(html, "lxml")
    except Exception as exc:
        logger.error("Failed to parse HTML in validator: %s", exc)
        # Return selectors with safe defaults
        result = []
        for sel in selectors:
            s = dict(sel)
            s["match_count"] = 0
            s["match_sample"] = None
            s["valid"] = False
            existing_warning = s.get("warning") or ""
            s["warning"] = (
                (existing_warning + " " if existing_warning else "") + "⚠ HTML parse failed"
            ).strip()
            result.append(s)
        return result

    validated: List[dict] = []
    for sel in selectors:
        s = dict(sel)  # shallow copy

        # Skip selector execution for fields the LLM determined are not on this page
        if not s.get("found", True):
            s["match_count"] = 0
            s["match_sample"] = None
            s["valid"] = False
            validated.append(s)
            continue

        css_selector: str = s.get("css_selector", "")

        match_count = 0
        match_sample: str | None = None

        if css_selector:
            try:
                matches = soup.select(css_selector)
                match_count = len(matches)
                if matches:
                    first_text = matches[0].get_text(separator=" ", strip=True)
                    match_sample = first_text[:MATCH_SAMPLE_LENGTH] if first_text else None
            except Exception as exc:
                logger.warning(
                    "CSS selector '%s' raised an error: %s", css_selector, exc
                )
                match_count = 0
                match_sample = None

        s["match_count"] = match_count
        s["match_sample"] = match_sample
        s["valid"] = match_count >= 1

        if not s["valid"]:
            existing_warning = s.get("warning") or ""
            s["warning"] = (
                (existing_warning + " " if existing_warning else "") + "⚠ No match found"
            ).strip()

        validated.append(s)

    return validated
